basic.showIcon(IconNames.Rollerskate)
basic.forever(function () {
    cuteBot.forward()
    basic.pause(200)
    cuteBot.motors(40, 100)
    basic.pause(100)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.motors(40, 100)
    basic.pause(100)
    cuteBot.forward()
    basic.pause(200)
})
